export const uiText = {
  appName: 'Cards Configurator',
  common: {
    back: 'Zurück',
    next: 'Weiter',
    loading: 'Wird geladen',
    templateFallback: 'Vorlage',
  },
  selection: {
    loading: {
      kicker: 'Loading registries',
      title: 'Cards Configurator',
      description: 'Die Konfigurationen werden geladen.',
    },
    emptyUseCases: {
      kicker: 'Auswahl',
      title: 'Keine aktiven Anwendungsfälle',
      description: 'Aktiviere mindestens einen Use Case in den Registries, damit der Konfigurator nutzbar ist.',
    },
    header: {
      title: 'Geführter Erstellungsprozess',
      lead: 'Wähle einen Anwendungsfall, ein Design und die Inhalte. Die Oberfläche führt dich Schritt für Schritt zu einer druckfähigen Freigabe.',
    },
    autosave: {
      label: 'Automatisch gespeichert',
      fallback: 'Automatisch gespeichert',
    },
    wizardSteps: {
      selection: {
        title: 'Auswahl',
        description: 'Zuerst den passenden Anwendungsfall wählen.',
        hint: 'Wähle zuerst einen Anwendungsfall, damit die passenden Optionen erscheinen.',
      },
      product: {
        title: 'Produkt',
        description: 'Dann das passende Format auswählen.',
        hint: 'Jetzt das Produkt auswählen. Danach geht es direkt zum Design.',
      },
      design: {
        title: 'Design',
        description: 'Eine Vorlage für den gewählten Einsatz auswählen.',
        hint: 'Ein Design auswählen, das zum Produkt und Use Case passt.',
      },
      content: {
        title: 'Inhalte',
        description: 'Texte, Medien und Anpassungen prüfen.',
        hint: 'Texte und Medien prüfen, dann die finale Vorschau kontrollieren.',
      },
      review: {
        title: 'Prüfen',
        description: 'Freigeben und den Auftrag erstellen.',
        hint: 'Alles prüfen und den Auftrag freigeben.',
      },
    },
    buttons: {
      reset: 'Konfiguration zurücksetzen',
      resetNew: 'Neue Konfiguration starten',
      resetHint: 'Zurücksetzen entfernt die aktuelle Auswahl und startet mit einem leeren Entwurf.',
      resetLockedHint: 'Dieser Entwurf ist freigegeben und gesperrt. Starte eine neue Konfiguration, um Änderungen vorzunehmen.',
      resetPending: 'Neustart...',
      back: 'Zurück',
      next: 'Weiter',
      productSwitch: 'Produkt wechseln',
      productCancel: 'Abbrechen',
      backToContent: 'Zur Inhalte',
      toReview: 'Zur Prüfung',
      release: 'Design freigeben',
      createOrder: 'Auftrag erstellen',
      releaseLoading: 'Freigabe läuft...',
      createOrderLoading: 'Auftrag wird erstellt...',
    },
    sections: {
      selection: '1. Auswahl',
      product: '2. Produkt',
      design: '3. Design',
      designWithoutProduct: '2. Design',
      contentWithProduct: '4. Inhalte',
      contentWithoutProduct: '3. Inhalte',
      reviewWithProduct: '5. Prüfen',
      reviewWithoutProduct: '4. Prüfen',
    },
    emptyTemplates: {
      kicker: 'Design',
      title: 'Keine passenden Templates',
      description: 'Wähle einen anderen Use Case oder ein anderes Produkt, damit wieder Vorlagen erscheinen.',
    },
    preview: {
      liveTitle: 'Live-Vorschau',
      approvalTitle: 'Freigabevorschau',
      liveVisible: 'Live-Vorschau sichtbar',
      approvalVisible: 'Freigabe-Mockup sichtbar',
      previewHidden: 'Wird nach Auswahl eingeblendet',
      empty: 'Sobald ein Design gewählt ist, erscheint hier die Vorschau.',
      expand: 'Vorschau vergrößern',
      collapse: 'Verkleinern',
      loading: 'Vorschau wird geladen…',
      liveHint: 'Live-Vorschau nutzt gerenderte Template-Elemente, sobald sie verfügbar sind.',
      note: 'Änderungen an Texten, Medien und Varianten erscheinen direkt in derselben Vorschau wie später im Druck.',
      mockupTitle: 'Produkt-Mockup',
      qrPlaceholder: 'QR-Platzhalter wird angezeigt, bis eine URL eingegeben wurde',
    },
    feedback: {
      title: 'Rückmeldungen',
      hint: 'Hinweise',
      qualityTitle: 'Qualitätsprüfung',
      empty: 'Noch keine kritischen Rückmeldungen.',
      blockingSummary: 'Probleme verhindern den Abschluss. Prüfe die markierten Felder.',
    },
    content: {
      titleWithProduct: '4. Inhalte',
      titleWithoutProduct: '3. Inhalte',
      eyebrow: 'Inhalte',
      summary: 'Texte, Varianten und Medien',
      meta: 'Vorlage für den gewählten Einsatzbereich',
      hint: 'Passe Varianten und Felder an. Die Vorschau bleibt separat sichtbar.',
      variants: 'Layoutvarianten',
      fields: 'Felder',
      assetReset: 'Zurücksetzen',
      contentReset: 'Inhalte zurücksetzen',
      layoutReset: 'Layout zurücksetzen',
    },
    productChange: {
      title: 'Produktwechsel setzt die aktuelle Vorlage zurück.',
      bodyPrefix: 'Beim Wechsel auf',
      bodySuffix: 'gehen die gewählte Vorlage, Variante und lokale Eingaben für diesen Entwurf verloren.',
    },
    productDetail: {
      selected: 'Ausgewähltes Produkt',
      available: 'Für den gewählten Einsatz verfügbar',
    },
    review: {
      eyebrow: 'Freigabe',
      approvedAtPrefix: 'Freigegeben am',
      proofCheckbox: 'Ich habe die Vorschau geprüft',
      readyHint: 'Der finale Zustand wird jetzt geprüft. Nach der Freigabe kann der Auftrag erstellt werden.',
      approvedStatus: 'Freigabe abgeschlossen',
      pendingStatus: 'Freigabe und Auftragserstellung',
      confirmedTitle: 'Prüfung bestätigt',
    },
    errors: {
      bootstrapUnavailable: 'Die Konfiguration ist derzeit nicht verfügbar.',
      validationUnavailable: 'Die Qualitätsprüfung ist derzeit nicht verfügbar.',
      fileUnavailable: 'Die Datei konnte nicht verarbeitet werden.',
      approvalUnavailable: 'Die Freigabe konnte nicht gespeichert werden.',
      resetUnavailable: 'Der Entwurf konnte nicht zurückgesetzt werden.',
      orderUnavailable: 'Der Auftrag konnte nicht erstellt werden.',
    },
  },
  order: {
    loading: {
      kicker: 'Auftrag wird geladen',
      title: 'Erfolgsansicht',
      description: 'Die Auftragsdaten werden vorbereitet.',
    },
    error: {
      kicker: 'Auftrag',
      title: 'Auftrag konnte nicht geladen werden',
      description: 'Der Auftrag konnte nicht geladen werden.',
    },
    created: {
      kicker: 'Auftrag erstellt',
      summary: 'Dein Auftrag ist gespeichert und bereit für die Produktion.',
      previewTitle: 'Vorschau',
      previewLoaded: 'Vorschau geladen',
      previewLoading: 'Vorschau wird geladen',
      previewErrorTitle: 'Vorschau konnte nicht geladen werden',
      previewErrorDescription: 'Die Produktion ist trotzdem gespeichert. Öffne die Produktionsansicht, um weiterzuarbeiten.',
      previewEmptyTitle: 'Keine Vorschau verfügbar',
      previewEmptyDescription: 'Die Auftragsdaten sind gespeichert. Öffne die Produktionsansicht, um weiterzuarbeiten.',
      mockupTitle: 'Produkt-Mockup',
      mockupLoaded: 'Mockup geladen',
      mockupLoading: 'Mockup wird geladen',
      mockupErrorTitle: 'Mockup konnte nicht geladen werden',
      mockupErrorDescription: 'Das Mockup ist trotzdem gespeichert.',
      mockupEmptyTitle: 'Kein Mockup verfügbar',
      mockupEmptyDescription: 'Für diesen Auftrag wurde kein Mockup gespeichert.',
      nextStepTitle: 'Produktions-PDF prüfen',
      nextStepLead: 'In der Produktionsansicht siehst du dieselbe Geometrie wie in der Vorschau. Danach kannst du den Auftrag erneut öffnen oder weiter im Workflow arbeiten.',
      nextStepStatus: 'Bereit für die Produktion',
      nextStepPreview: 'Vorschau',
      approvedAtPrefix: 'Freigegeben am',
      snapshotTitle: 'Gespeicherte Auftragsdaten',
      snapshotLead: 'Die Detailansicht zeigt nur gespeicherte Snapshots und finale Artefakte.',
      snapshotCustomer: 'Kunde',
      snapshotUseCase: 'Use Case',
      snapshotProduct: 'Produkt',
      snapshotTemplate: 'Template',
      snapshotVariant: 'Variante',
      snapshotApprovedAt: 'Freigabezeitpunkt',
      snapshotRenderEngine: 'Render Engine',
      snapshotValidation: 'Validierung',
      snapshotTextValues: 'Kundeneingaben',
      snapshotAssetValues: 'Asset-Zuordnungen',
      assetsTitle: 'Hochgeladene Assets',
      assetsEmpty: 'Keine gespeicherten Assets vorhanden.',
    },
    actions: {
      production: 'Zur Produktionsansicht',
      downloadPdf: 'Produktions-PDF herunterladen',
      pdfLoading: 'Produktions-PDF wird erzeugt',
      reopen: 'Auftrag erneut öffnen',
      productionOpen: 'Produktionsansicht öffnen',
      pdfDownload: 'PDF herunterladen',
      mockupOpen: 'Mockup öffnen',
    },
  },
  proof: {
    loading: {
      kicker: 'Proof wird geladen',
      title: 'DesignRenderer',
    },
    error: {
      title: 'Proof nicht verfügbar',
      description: 'Die Renderer-Proofansicht konnte nicht geladen werden.',
    },
    header: {
      kicker: 'Renderer-Proof',
      title: 'DesignRenderer',
    },
  },
  errors: {
    selectionLoad: 'Die Konfiguration ist derzeit nicht verfügbar.',
    validationLoad: 'Die Qualitätsprüfung ist derzeit nicht verfügbar.',
    fileUpload: 'Die Datei konnte nicht verarbeitet werden.',
    approval: 'Die Freigabe konnte nicht gespeichert werden.',
    reset: 'Der Entwurf konnte nicht zurückgesetzt werden.',
    orderCreate: 'Der Auftrag konnte nicht erstellt werden.',
    qrPreview: 'Die QR-Vorschau konnte nicht geladen werden.',
    orderLoad: 'Der Auftrag konnte nicht geladen werden.',
    orderFixtureLoad: 'Die Produktionsansicht konnte nicht geladen werden.',
    proofLoad: 'Die Renderer-Proofansicht konnte nicht geladen werden.',
  },
} as const;
