export const uiText = {
  appName: 'cards-configurator',
  common: {
    back: 'Zurück',
    next: 'Weiter',
    loading: 'Wird geladen',
    designFallback: 'Design',
  },
  selection: {
    loading: {
      kicker: 'Loading registries',
      title: 'cards-configurator',
      description: 'Die Konfigurationen werden geladen.',
    },
    emptyUseCases: {
      kicker: 'Auswahl',
      title: 'Keine aktiven Anwendungsfälle',
      description: 'Aktiviere mindestens einen Use Case in den Registries, damit der Konfigurator nutzbar ist.',
    },
    header: {
      title: 'Geführter Erstellungsprozess',
      lead: 'Wähle zuerst ein Produkt, danach Design, Inhalte und Prüfung. Die Oberfläche zeigt immer nur den nächsten sinnvollen Schritt.',
    },
    autosave: {
      saved: 'Gespeichert',
    },
    wizardSteps: {
      product: {
        title: 'Produkt',
        description: 'Das passende Format auswählen.',
        hint: 'Wähle zuerst das Produkt, das gedruckt werden soll.',
      },
      design: {
        title: 'Design',
        description: 'Ein Design für das Produkt auswählen.',
        hint: 'Wähle ein Design, das zum Produkt passt.',
      },
      content: {
        title: 'Inhalte',
        description: 'Texte, Medien und Anpassungen prüfen.',
        hint: 'Formuliere die Inhalte und kontrolliere die Vorschau.',
      },
      review: {
        title: 'Prüfen',
        description: 'Freigeben und den Auftrag erstellen.',
        hint: 'Prüfe alles noch einmal und gib das Design frei.',
      },
    },
    buttons: {
      reset: 'Konfiguration zurücksetzen',
      resetNew: 'Neue Konfiguration starten',
      resetHint: 'Zurücksetzen entfernt die aktuelle Auswahl und startet mit einem leeren Entwurf.',
      resetLockedHint: 'Dieser Entwurf ist freigegeben und gesperrt. Starte eine neue Konfiguration, um Änderungen vorzunehmen.',
      resetPending: 'Neustart...',
      resetConfirm: 'Möchtest du die aktuelle Konfiguration wirklich zurücksetzen?',
      more: 'Mehr',
      back: 'Zurück',
      next: 'Weiter',
      productSwitch: 'Produkt wechseln',
      productCancel: 'Abbrechen',
      backToContent: 'Zu den Inhalten',
      toReview: 'Weiter zur Prüfung',
      release: 'Design freigeben',
      createOrder: 'Auftrag erstellen',
      releaseLoading: 'Freigabe läuft...',
      createOrderLoading: 'Auftrag wird erstellt...',
    },
    sections: {
      product: '1. Produkt',
      design: '2. Design',
      content: '3. Inhalte',
      review: '4. Prüfen',
    },
    emptyDesigns: {
      kicker: 'Design',
      title: 'Keine passenden Designs',
      description: 'Wähle einen anderen Use Case oder ein anderes Produkt, damit wieder Designs erscheinen.',
    },
    preview: {
      liveTitle: 'Live-Vorschau',
      approvalTitle: 'Freigabevorschau',
      empty: 'Sobald ein Design gewählt ist, erscheint hier die Vorschau.',
      expand: 'Vorschau vergrößern',
      collapse: 'Verkleinern',
      loading: 'Vorschau wird geladen…',
      liveHint: 'Live-Vorschau nutzt gerenderte Designelemente, sobald sie verfügbar sind.',
      mockupTitle: 'Produkt-Mockup',
    },
    feedback: {
      blockingSummary: 'Probleme verhindern den Abschluss. Prüfe die markierten Felder.',
    },
    content: {
      title: 'Personalisiere deine Karte',
      designPrefix: 'Design: ',
      designChange: 'Design ändern',
      charUnit: 'Zeichen',
      lineLimit: 'Maximal {count} Zeilen',
      optional: 'optional',
      required: 'Pflicht',
      assetUpload: '{field} hochladen',
      assetReplace: 'Ersetzen',
      assetReplaceLabel: '{field} ersetzen',
      assetRemove: 'Entfernen',
      assetRemoveLabel: '{field} entfernen',
      assetAdjust: '{field} anpassen',
      adjustmentReset: 'Bildanpassungen zurücksetzen',
      suggestionsLabel: 'Vorschläge für {field}',
    },
    productChange: {
      title: 'Produktwechsel setzt das aktuelle Design zurück.',
      bodyPrefix: 'Beim Wechsel auf',
      bodySuffix: 'gehen das gewählte Design und lokale Eingaben für diesen Entwurf verloren.',
    },
    review: {
      eyebrow: 'Freigabe',
      approvedAtPrefix: 'Freigegeben am',
      proofCheckbox: 'Ich habe die Vorschau geprüft',
      readyHint: 'Der finale Zustand wird jetzt geprüft. Nach der Freigabe kann der Auftrag erstellt werden.',
      approvedStatus: 'Freigabe abgeschlossen',
      pendingStatus: 'Freigabe und Auftragserstellung',
      confirmedTitle: 'Prüfung bestätigt',
      checkTitle: 'Prüfpunkte',
      checkPending: 'offen',
      meta: 'Zusammenfassung der letzten Prüfung',
    },
    errors: {
      bootstrapUnavailable: 'Die Konfiguration ist derzeit nicht verfügbar.',
      validationUnavailable: 'Die Qualitätsprüfung ist derzeit nicht verfügbar.',
      fileUnavailable: 'Die Datei konnte nicht verarbeitet werden.',
      approvalUnavailable: 'Die Freigabe konnte nicht gespeichert werden.',
      resetUnavailable: 'Der Entwurf konnte nicht zurückgesetzt werden.',
      orderUnavailable: 'Der Auftrag konnte nicht erstellt werden.',
    },
  },
  order: {
    loading: {
      kicker: 'Auftrag wird geladen',
      title: 'Erfolgsansicht',
      description: 'Die Auftragsdaten werden vorbereitet.',
    },
    error: {
      kicker: 'Auftrag',
      title: 'Auftrag konnte nicht geladen werden',
      description: 'Der Auftrag konnte nicht geladen werden.',
    },
    created: {
      kicker: 'Auftrag erstellt',
      summary: 'Dein Auftrag ist gespeichert und bereit für die Produktion.',
      previewTitle: 'Vorschau',
      previewLoaded: 'Vorschau geladen',
      previewLoading: 'Vorschau wird geladen',
      previewErrorTitle: 'Vorschau konnte nicht geladen werden',
      previewErrorDescription: 'Die Produktion ist trotzdem gespeichert. Öffne die Produktionsansicht, um weiterzuarbeiten.',
      previewEmptyTitle: 'Keine Vorschau verfügbar',
      previewEmptyDescription: 'Die Auftragsdaten sind gespeichert. Öffne die Produktionsansicht, um weiterzuarbeiten.',
      mockupTitle: 'Produkt-Mockup',
      mockupLoaded: 'Mockup geladen',
      mockupLoading: 'Mockup wird geladen',
      mockupErrorTitle: 'Mockup konnte nicht geladen werden',
      mockupErrorDescription: 'Das Mockup ist trotzdem gespeichert.',
      mockupEmptyTitle: 'Kein Mockup verfügbar',
      mockupEmptyDescription: 'Für diesen Auftrag wurde kein Mockup gespeichert.',
      nextStepTitle: 'Produktions-PDF prüfen',
      nextStepLead: 'In der Produktionsansicht siehst du dieselbe Geometrie wie in der Vorschau. Danach kannst du den Auftrag erneut öffnen oder weiter im Workflow arbeiten.',
      nextStepStatus: 'Bereit für die Produktion',
      nextStepPreview: 'Vorschau',
      approvedAtPrefix: 'Freigegeben am',
      snapshotTitle: 'Gespeicherte Auftragsdaten',
      snapshotLead: 'Die Detailansicht zeigt nur gespeicherte Snapshots und finale Artefakte.',
      snapshotCustomer: 'Kunde',
      snapshotUseCase: 'Use Case',
      snapshotProduct: 'Produkt',
      snapshotDesign: 'Design',
      snapshotVariant: 'Variante',
      snapshotApprovedAt: 'Freigabezeitpunkt',
      snapshotRenderEngine: 'Render Engine',
      snapshotValidation: 'Validierung',
      snapshotTextValues: 'Kundeneingaben',
      snapshotAssetValues: 'Asset-Zuordnungen',
      assetsTitle: 'Hochgeladene Assets',
      assetsEmpty: 'Keine gespeicherten Assets vorhanden.',
    },
    actions: {
      production: 'Zur Produktionsansicht',
      downloadPdf: 'Produktions-PDF herunterladen',
      pdfLoading: 'Produktions-PDF wird erzeugt',
      reopen: 'Auftrag erneut öffnen',
      productionOpen: 'Produktionsansicht öffnen',
      pdfDownload: 'PDF herunterladen',
      mockupOpen: 'Mockup öffnen',
    },
  },
  proof: {
    loading: {
      kicker: 'Proof wird geladen',
      title: 'DesignRenderer',
    },
    error: {
      title: 'Proof nicht verfügbar',
      description: 'Die Renderer-Proofansicht konnte nicht geladen werden.',
    },
    header: {
      kicker: 'Renderer-Proof',
      title: 'DesignRenderer',
    },
  },
  errors: {
    selectionLoad: 'Die Konfiguration ist derzeit nicht verfügbar.',
    validationLoad: 'Die Qualitätsprüfung ist derzeit nicht verfügbar.',
    fileUpload: 'Die Datei konnte nicht verarbeitet werden.',
    approval: 'Die Freigabe konnte nicht gespeichert werden.',
    reset: 'Der Entwurf konnte nicht zurückgesetzt werden.',
    orderCreate: 'Der Auftrag konnte nicht erstellt werden.',
    qrPreview: 'Die QR-Vorschau konnte nicht geladen werden.',
    orderLoad: 'Der Auftrag konnte nicht geladen werden.',
    orderFixtureLoad: 'Die Produktionsansicht konnte nicht geladen werden.',
    proofLoad: 'Die Renderer-Proofansicht konnte nicht geladen werden.',
  },
} as const;
